In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv("../Dataset/Global_world_t.csv")

In [3]:
df

Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0    Afghanistan               60           AF                58.10%   
1        Albania              105           AL                43.10%   
2        Algeria               18           DZ                17.40%   
3        Andorra              164           AD                40.00%   
4         Angola               26           AO                47.50%   
..           ...              ...          ...                   ...   
190    Venezuela               32           VE                24.50%   
191      Vietnam              314           VN                39.30%   
192        Yemen               56           YE                44.60%   
193       Zambia               25           ZM                32.10%   
194     Zimbabwe               38           ZW                41.90%   

    Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0          652,230           323,000       32.49          93.0   
1           28,748             9,000       11.78         355.0   
2        2,381,741           317,000       24.28         213.0   
3              468               NaN        7.20         376.0   
4        1,246,700           117,000       40.73         244.0   
..             ...               ...         ...           ...   
190        912,050           343,000       17.88          58.0   
191        331,210           522,000       16.75          84.0   
192        527,968            40,000       30.45         967.0   
193        752,618            16,000       36.19         260.0   
194        390,757            51,000       30.68         263.0   

    Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0                Kabul         8,672  ...                           78.40%   
1               Tirana         4,536  ...                           56.90%   
2              Algiers       150,006  ...                           28.10%   
3     Andorra la Vella           469  ...                           36.40%   
4               Luanda        34,693  ...                           33.40%   
..                 ...           ...  ...                              ...   
190            Caracas       164,175  ...                           45.80%   
191              Hanoi       192,668  ...                           43.50%   
192              Sanaa        10,609  ...                           81.00%   
193             Lusaka         5,141  ...                           27.50%   
194             Harare        10,983  ...                           25.80%   

    Physicians per thousand  Population  \
0                      0.28  38,041,754   
1                      1.20   2,854,191   
2                      1.72  43,053,054   
3                      3.33      77,142   
4                      0.21  31,825,295   
..                      ...         ...   
190                    1.92  28,515,829   
191                    0.82  96,462,106   
192                    0.31  29,161,922   
193                    1.19  17,861,030   
194                    0.21  14,645,468   

     Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                       48.90%           9.30%         71.40%   
1                                       55.70%          18.60%         36.60%   
2                                       41.20%          37.20%         66.10%   
3                                          NaN             NaN            NaN   
4                                       77.50%           9.20%         49.10%   
..                                         ...             ...            ...   
190                                     59.70%             NaN         73.30%   
191                                     77.40%          19.10%         37.60%   
192                                     38.00%             NaN         26.60%   
193                                     74.60%          16.20%         15.60%   
194   

In [4]:
df.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   Country                                    195 non-null    object 
 1   Density
(P/Km2)                            195 non-null    object 
 2   Abbreviation                               188 non-null    object 
 3   Agricultural Land( %)                      188 non-null    object 
 4   Land Area(Km2)                             194 non-null    object 
 5   Armed Forces size                          171 non-null    object 
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object 
 9   Co2-Emissions                              188 non-null    object 
 10  CPI                       

In [6]:
df = df.rename( columns = {'Agricultural Land( %)' : 'Agricultural_Land'})
df = df.rename( columns = {'Land Area(Km2)' : 'Land_Area'})
df = df.rename( columns = {'Armed Forces size' : 'Armed_Forces_size'})
df = df.rename( columns = {'Birth Rate' : 'Birth_Rate'})
df = df.rename( columns = {'Calling Code' : 'Calling_Code'})
df = df.rename( columns = {'Capital/Major City' : 'Major_City'})
df = df.rename( columns = {'CPI Change (%)' : 'CPI_Change'})
df = df.rename( columns = {'Fertility Rate' : 'Fertility_Rate'})
df = df.rename( columns = {'Gasoline Price' : 'Gasoline_Price'})
df = df.rename( columns = {'Gross primary education enrollment (%)' : 'Gross_primary_education_enrollment'})
df = df.rename( columns = {'Gross tertiary education enrollment (%)' : 'Gross_tertiary_education_enrollment'})
df = df.rename( columns = {'Infant mortality ' : 'Infant_mortality'})
df = df.rename( columns = {'Largest city' : 'Largest_city'})
df = df.rename( columns = {'Life expectancy' : 'Life_expectancy'})
df = df.rename( columns = {'Maternal mortality ratio' : 'Maternal_mortality_ratio'})
df = df.rename( columns = {'Minimum wage' : 'Minimum_wage'})
df = df.rename( columns = {'Official language' : 'Official_language'})
df = df.rename( columns = {'Out of pocket health expenditure' : 'Out_of_pocket_health_expenditure'})
df = df.rename( columns = {'Physicians per thousand' : 'Physicians_per_thousand'})
df = df.rename( columns = {'Population: Labor force participation (%)' : 'Population_Labor_force_participation'})
df = df.rename( columns = {'Tax revenue (%)' : 'Tax_revenue'})
df = df.rename( columns = {'Total tax rate' : 'Total_tax_rate'})
df = df.rename( columns = {'Unemployment rate' : 'Unemployment_rate'})
df = df.rename( columns = {'Forested Area (%)' : 'Forested_Area'})
df = df.rename( columns = {'Co2-Emissions' : 'Co2_Emissions'})
df = df.rename( columns = {'Currency-Code' : 'Currency_Code'})
df = df.rename( columns = {'Infant mortality' : 'Infant_mortality'})
df = df.rename( columns = {'Density\n(P/Km2)' : 'Density'})

In [7]:
df

Country Density Abbreviation Agricultural_Land  Land_Area  \
0    Afghanistan      60           AF            58.10%    652,230   
1        Albania     105           AL            43.10%     28,748   
2        Algeria      18           DZ            17.40%  2,381,741   
3        Andorra     164           AD            40.00%        468   
4         Angola      26           AO            47.50%  1,246,700   
..           ...     ...          ...               ...        ...   
190    Venezuela      32           VE            24.50%    912,050   
191      Vietnam     314           VN            39.30%    331,210   
192        Yemen      56           YE            44.60%    527,968   
193       Zambia      25           ZM            32.10%    752,618   
194     Zimbabwe      38           ZW            41.90%    390,757   

    Armed_Forces_size  Birth_Rate  Calling_Code        Major_City  \
0             323,000       32.49          93.0             Kabul   
1               9,000       11.78         355.0            Tirana   
2             317,000       24.28         213.0           Algiers   
3                 NaN        7.20         376.0  Andorra la Vella   
4             117,000       40.73         244.0            Luanda   
..                ...         ...           ...               ...   
190           343,000       17.88          58.0           Caracas   
191           522,000       16.75          84.0             Hanoi   
192            40,000       30.45         967.0             Sanaa   
193            16,000       36.19         260.0            Lusaka   
194            51,000       30.68         263.0            Harare   

    Co2_Emissions  ... Out_of_pocket_health_expenditure  \
0           8,672  ...                           78.40%   
1           4,536  ...                           56.90%   
2         150,006  ...                           28.10%   
3             469  ...                           36.40%   
4          34,693  ...                           33.40%   
..            ...  ...                              ...   
190       164,175  ...                           45.80%   
191       192,668  ...                           43.50%   
192        10,609  ...                           81.00%   
193         5,141  ...                           27.50%   
194        10,983  ...                           25.80%   

    Physicians_per_thousand  Population  Population_Labor_force_participation  \
0                      0.28  38,041,754                                48.90%   
1                      1.20   2,854,191                                55.70%   
2                      1.72  43,053,054                                41.20%   
3                      3.33      77,142                                   NaN   
4                      0.21  31,825,295                                77.50%   
..                      ...         ...                                   ...   
190                    1.92  28,515,829                                59.70%   
191                    0.82  96,462,106                                77.40%   
192                    0.31  29,161,922                                38.00%   
193                    1.19  17,861,030                                74.60%   
194                    0.21  14,645,468                                83.10%   

    Tax_revenue Total_tax_rate Unemployment_rate Urban_population   Latitude  \
0         9.30%         71.40%            11.12%        9,797,273  33.939110   
1        18.60%         36.60%            12.33%        1,747,593  41.153332   
2        37.20%         66.10%            11.70%       31,510,100  28.033886   
3           NaN            NaN               NaN           67,873  42.506285   
4         9.20%         49.10%             6.89%       21,061,025 -11.202692   
..          ...            ...               ...              ...        ...   
190         NaN         73.30%             8.80%       25,162,368   6.423750   
191      19.10%  

In [8]:
df.Abbreviation = df.Abbreviation.fillna(0)
df.Agricultural_Land = df.Agricultural_Land.fillna(0)
df.Armed_Forces_size = df.Armed_Forces_size.fillna(0)
df.Birth_Rate = df.Birth_Rate.fillna(0)
df.Calling_Code = df.Calling_Code.fillna(0)
df.Major_City = df.Major_City.fillna(0)
df.CPI = df.CPI.fillna(0)
df.CPI_Change = df.CPI_Change.fillna(0)
df.Co2_Emissions = df.Co2_Emissions.fillna(0)
df.Currency_Code = df.Currency_Code.fillna(0)
df.Fertility_Rate = df.Fertility_Rate.fillna(0)
df.Forested_Area = df.Forested_Area.fillna(0)
df.Gasoline_Price = df.Gasoline_Price.fillna(0)
df.GDP = df.GDP.fillna(0)
df.Largest_city = df.Largest_city.fillna(0)
df.Life_expectancy = df.Life_expectancy.fillna(0)
df.Maternal_mortality_ratio = df.Maternal_mortality_ratio.fillna(0)
df.Minimum_wage = df.Minimum_wage.fillna(0)
df.Official_language = df.Official_language.fillna(0)
df.Physicians_per_thousand = df.Physicians_per_thousand.fillna(0)
df.Population = df.Population.fillna(0)
df.Population_Labor_force_participation = df.Population_Labor_force_participation.fillna(0)
df.Tax_revenue = df.Tax_revenue.fillna(0)
df.Unemployment_rate = df.Unemployment_rate.fillna(0)
df.Urban_population = df.Urban_population.fillna(0)
df.Latitude = df.Latitude.fillna(0)
df.Longitude = df.Longitude.fillna(0)
df.Gross_primary_education_enrollment = df.Gross_primary_education_enrollment.fillna(0)
df.Gross_tertiary_education_enrollment = df.Gross_tertiary_education_enrollment.fillna(0)
df.Total_tax_rate = df.Total_tax_rate.fillna(0)
df.Out_of_pocket_health_expenditure = df.Out_of_pocket_health_expenditure.fillna(0)
df.Land_Area = df.Land_Area.fillna(0)
df.Infant_mortality = df.Infant_mortality.fillna(0)

In [9]:
df.isnull().sum()

Country                                 0
Density                                 0
Abbreviation                            0
Agricultural_Land                       0
Land_Area                               0
Armed_Forces_size                       0
Birth_Rate                              0
Calling_Code                            0
Major_City                              0
Co2_Emissions                           0
CPI                                     0
CPI_Change                              0
Currency_Code                           0
Fertility_Rate                          0
Forested_Area                           0
Gasoline_Price                          0
GDP                                     0
Gross_primary_education_enrollment      0
Gross_tertiary_education_enrollment     0
Infant_mortality                        0
Largest_city                            0
Life_expectancy                         0
Maternal_mortality_ratio                0
Minimum_wage                      

In [10]:
df.Infant_mortality.unique()

array([47.9,  7.8, 20.1,  2.7, 51.6,  5. ,  8.8, 11. ,  3.1,  2.9, 19.2,
        8.3,  6.1, 25.1, 11.3,  2.6, 11.2, 60.5, 24.8, 21.8, 30. , 12.8,
        9.8,  5.9, 49. , 41. , 59.4, 16.7, 24. , 50.6,  4.3, 84.5, 71.4,
        6.2,  7.4, 12.2, 51.3, 36.2,  7.6,  4. ,  3.7,  1.9, 68.2,  3.6,
       49.8, 32.9, 24.1, 18.1, 11.8, 62.6, 31.3,  2.1,  0. , 39.1, 21.6,
        1.4,  3.4, 32.7, 39. ,  8.7, 34.9, 13.7, 22.1, 64.9, 54. , 49.5,
       15.1,  1.5, 29.9, 21.1, 12.4, 22.5,  3. ,  1.8, 13.9, 30.6, 41.2,
        6.7, 16.9, 37.6,  3.3,  6.4, 65.7, 53.5, 10.2, 38.2, 35.3, 62. ,
       27.4, 51.5, 13.6, 25.6, 14. ,  2.3, 36.8, 29. , 26.7,  4.7, 15.7,
       48. , 75.7, 57.2, 16.6, 13.1, 38. , 17.2, 11.1,  3.8,  5.8, 27. ,
       14.9, 14.8,  1.7, 24.4,  6. , 31.8,  4.8, 78.5,  4.6, 17.1, 76.6,
       28.5, 63.7,  2.5, 42.1,  2.2, 30.4, 39.3, 47.4, 13.4, 16.4, 14.6,
        9.1, 20.6, 33.8,  7.5,  6.5,  5.6, 19.1, 22.3, 21.4, 16.5, 42.9,
       40.4, 33.9])

In [11]:
df.Infant_mortality = df.Infant_mortality.replace('[nan]', '', regex=True).astype('float64')

In [12]:
df.Infant_mortality.unique()

array([47.9,  7.8, 20.1,  2.7, 51.6,  5. ,  8.8, 11. ,  3.1,  2.9, 19.2,
        8.3,  6.1, 25.1, 11.3,  2.6, 11.2, 60.5, 24.8, 21.8, 30. , 12.8,
        9.8,  5.9, 49. , 41. , 59.4, 16.7, 24. , 50.6,  4.3, 84.5, 71.4,
        6.2,  7.4, 12.2, 51.3, 36.2,  7.6,  4. ,  3.7,  1.9, 68.2,  3.6,
       49.8, 32.9, 24.1, 18.1, 11.8, 62.6, 31.3,  2.1,  0. , 39.1, 21.6,
        1.4,  3.4, 32.7, 39. ,  8.7, 34.9, 13.7, 22.1, 64.9, 54. , 49.5,
       15.1,  1.5, 29.9, 21.1, 12.4, 22.5,  3. ,  1.8, 13.9, 30.6, 41.2,
        6.7, 16.9, 37.6,  3.3,  6.4, 65.7, 53.5, 10.2, 38.2, 35.3, 62. ,
       27.4, 51.5, 13.6, 25.6, 14. ,  2.3, 36.8, 29. , 26.7,  4.7, 15.7,
       48. , 75.7, 57.2, 16.6, 13.1, 38. , 17.2, 11.1,  3.8,  5.8, 27. ,
       14.9, 14.8,  1.7, 24.4,  6. , 31.8,  4.8, 78.5,  4.6, 17.1, 76.6,
       28.5, 63.7,  2.5, 42.1,  2.2, 30.4, 39.3, 47.4, 13.4, 16.4, 14.6,
        9.1, 20.6, 33.8,  7.5,  6.5,  5.6, 19.1, 22.3, 21.4, 16.5, 42.9,
       40.4, 33.9])

In [13]:
df.Land_Area.unique()

array(['652,230', '28,748', '2,381,741', '468', '1,246,700', '443',
       '2,780,400', '29,743', '7,741,220', '83,871', '86,600', '13,880',
       '765', '148,460', '430', '207,600', '30,528', '22,966', '112,622',
       '38,394', '1,098,581', '51,197', '581,730', '8,515,770', '5,765',
       '110,879', '274,200', '27,830', '322,463', '4,033', '181,035',
       '475,440', '9,984,670', '622,984', '1,284,000', '756,096',
       '9,596,960', '1,138,910', '2,235', '342,000', '51,100', '56,594',
       '110,860', '9,251', '78,867', '2,344,858', '43,094', '23,200',
       '751', '48,670', '283,561', '1,001,450', '21,041', '28,051',
       '117,600', '45,228', '17,364', '1,104,300', '18,274', '338,145',
       '643,801', '267,667', '11,300', '69,700', '357,022', '238,533',
       '131,957', '349', '108,889', '245,857', '36,125', '214,969',
       '27,750', '0', '112,090', '93,028', '103,000', '3,287,263',
       '1,904,569', '1,648,195', '438,317', '70,273', '20,770', '301,340',
       '10,9

In [14]:
df.Land_Area = df.Land_Area.replace('[,]', '0', regex=True).astype('int64')

In [15]:
df.Land_Area = df.Land_Area.replace('[nan]', '', regex=True).astype('int64')

In [16]:
df.Land_Area.unique()

array([   6520230,     280748,  203810741,        468,  102460700,
              443,  207800400,     290743,  707410220,     830871,
           860600,     130880,        765,    1480460,        430,
          2070600,     300528,     220966,    1120622,     380394,
        100980581,     510197,    5810730,  805150770,      50765,
          1100879,    2740200,     270830,    3220463,      40033,
          1810035,    4750440,  909840670,    6220984,  102840000,
          7560096,  905960960,  101380910,      20235,    3420000,
           510100,     560594,    1100860,      90251,     780867,
        203440858,     430094,     230200,        751,     480670,
          2830561,  100010450,     210041,     280051,    1170600,
           450228,     170364,  101040300,     180274,    3380145,
          6430801,    2670667,     110300,     690700,    3570022,
          2380533,    1310957,        349,    1080889,    2450857,
           360125,    2140969,     270750,          0,    1120

In [17]:
df.dtypes

Country                                  object
Density                                  object
Abbreviation                             object
Agricultural_Land                        object
Land_Area                                 int64
Armed_Forces_size                        object
Birth_Rate                              float64
Calling_Code                            float64
Major_City                               object
Co2_Emissions                            object
CPI                                      object
CPI_Change                               object
Currency_Code                            object
Fertility_Rate                          float64
Forested_Area                            object
Gasoline_Price                           object
GDP                                      object
Gross_primary_education_enrollment       object
Gross_tertiary_education_enrollment      object
Infant_mortality                        float64
Largest_city                            

In [18]:
 df["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'The Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Ivory Coast',
       'Cape Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Republic of the Congo', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic',
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'The Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guatemal

1. Country

In [19]:
df.Country = df.Country.replace('[�]', '', regex=True).astype('object')

In [20]:
 df["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'The Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Ivory Coast',
       'Cape Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Republic of the Congo', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic',
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'The Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guatemal

In [21]:
df["Country"].value_counts()

Country
Afghanistan      1
Saint Lucia      1
Nicaragua        1
Niger            1
Nigeria          1
                ..
Grenada          1
Guatemala        1
Guinea           1
Guinea-Bissau    1
Zimbabwe         1
Name: count, Length: 195, dtype: int64

In [22]:
df.groupby("Country")[["Population", "Land_Area", "Density"]].count().head(10)

Population  Land_Area  Density
Country                                            
Afghanistan                   1          1        1
Albania                       1          1        1
Algeria                       1          1        1
Andorra                       1          1        1
Angola                        1          1        1
Antigua and Barbuda           1          1        1
Argentina                     1          1        1
Armenia                       1          1        1
Australia                     1          1        1
Austria                       1          1        1

2. Population Density

In [23]:
 df["Density"].unique()

array(['60', '105', '18', '164', '26', '223', '17', '104', '3', '109',
       '123', '39', '2,239', '1,265', '668', '47', '383', '108', '20',
       '11', '64', '4', '25', '83', '76', '463', '138', '95', '56', '8',
       '13', '153', '46', '467', '16', '100', '73', '106', '131', '139',
       '40', '137', '43', '96', '225', '71', '103', '313', '50', '35',
       '31', '67', '115', '49', '119', '9', '239', '57', '240', '81',
       '331', '167', '53', '70', '414', '2,003', '89', '107', '464',
       '151', '52', '93', '72', '400', '206', '273', '347', '7', '94',
       '147', '34', '32', '30', '667', '238', '242', '48', '203', '99',
       '1,802', '1,380', '329', '5', '626', '66', '784', '26,337', '2',
       '541', '508', '55', '19', '226', '214', '15', '287', '847', '58',
       '368', '124', '111', '248', '84', '525', '205', '301', '284',
       '566', '228', '87', '8,358', '114', '527', '341', '219', '68',
       '152', '110', '393', '229', '75', '118', '281', '36', '79', '314',
 

In [24]:
df.Density = df.Density.replace('[,]', '', regex=True).astype('int64')

In [25]:
 df["Density"].unique()

array([   60,   105,    18,   164,    26,   223,    17,   104,     3,
         109,   123,    39,  2239,  1265,   668,    47,   383,   108,
          20,    11,    64,     4,    25,    83,    76,   463,   138,
          95,    56,     8,    13,   153,    46,   467,    16,   100,
          73,   106,   131,   139,    40,   137,    43,    96,   225,
          71,   103,   313,    50,    35,    31,    67,   115,    49,
         119,     9,   239,    57,   240,    81,   331,   167,    53,
          70,   414,  2003,    89,   107,   464,   151,    52,    93,
          72,   400,   206,   273,   347,     7,    94,   147,    34,
          32,    30,   667,   238,   242,    48,   203,    99,  1802,
        1380,   329,     5,   626,    66,   784, 26337,     2,   541,
         508,    55,    19,   226,   214,    15,   287,   847,    58,
         368,   124,   111,   248,    84,   525,   205,   301,   284,
         566,   228,    87,  8358,   114,   527,   341,   219,    68,
         152,   110,

In [26]:
df["Density"].min()

2

In [27]:
df["Density"].max()

26337

In [28]:
(df.loc[df["Density"].idxmin(), ["Country", "Density"]])

Country    Mongolia
Density           2
Name: 114, dtype: object

In [29]:
(df.loc[df["Density"].idxmax(), ["Country", "Density"]])

Country    Monaco
Density     26337
Name: 113, dtype: object

In [30]:
low_threshold = df["Density"].quantile(0.05) 
low_density_countries = df[df["Density"] <= low_threshold][["Country", "Density"]]
low_density_countries

Country  Density
8     Australia        3
22     Botswana        4
32       Canada        4
71       Guyana        4
76      Iceland        3
97        Libya        4
108  Mauritania        5
114    Mongolia        2
119     Namibia        3
167    Suriname        4

In [31]:
high_threshold = df["Density"].quantile(0.95)
high_density_countries = df[df["Density"] >= high_threshold][["Country", "Density"]]
high_density_countries

Country  Density
12                          Bahrain     2239
13                       Bangladesh     1265
14                         Barbados      668
73                     Vatican City     2003
104                        Maldives     1802
106                           Malta     1380
111  Federated States of Micronesia      784
113                          Monaco    26337
133  Palestinian National Authority      847
156                       Singapore     8358

In [32]:
df[["Country", "Abbreviation"]]

Country Abbreviation
0    Afghanistan           AF
1        Albania           AL
2        Algeria           DZ
3        Andorra           AD
4         Angola           AO
..           ...          ...
190    Venezuela           VE
191      Vietnam           VN
192        Yemen           YE
193       Zambia           ZM
194     Zimbabwe           ZW

[195 rows x 2 columns]

In [33]:
 df["Abbreviation"].unique()

array(['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
       'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA',
       'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CI', 'CV', 'KH', 'CM', 'CA',
       'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 0, 'CR', 'HR', 'CU', 'CY',
       'CZ', 'CD', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER',
       'EE', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR',
       'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID',
       'IR', 'IQ', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KW',
       'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG',
       'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD',
       'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NR', 'NP', 'NL', 'NZ', 'NI',
       'NE', 'NG', 'KP', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE',
       'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS',
       'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG',

In [34]:
df.Abbreviation = df.Abbreviation.replace('[0]','', regex=True).astype('object')

In [35]:
 df["Abbreviation"].unique()

array(['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
       'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA',
       'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CI', 'CV', 'KH', 'CM', 'CA',
       'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 0, 'CR', 'HR', 'CU', 'CY',
       'CZ', 'CD', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER',
       'EE', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR',
       'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID',
       'IR', 'IQ', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KW',
       'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG',
       'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD',
       'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NR', 'NP', 'NL', 'NZ', 'NI',
       'NE', 'NG', 'KP', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE',
       'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS',
       'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG',

In [36]:
df['Abbreviation_Code'] = df['Abbreviation'].astype('category').cat.codes
df.corr(numeric_only=True)['Abbreviation_Code'].sort_values(ascending=False)

Abbreviation_Code           1.000000
Birth_Rate                  0.158854
Fertility_Rate              0.153322
Longitude                   0.105405
Calling_Code                0.104931
Infant_mortality            0.099362
Life_expectancy             0.082604
Maternal_mortality_ratio    0.074913
Density                     0.025826
Land_Area                  -0.033090
Physicians_per_thousand    -0.089489
Latitude                   -0.117730
Name: Abbreviation_Code, dtype: float64

4. Agricultural land

In [37]:
df['Agricultural_Land'].describe()

count     195
unique    169
top         0
freq        7
Name: Agricultural_Land, dtype: int64

In [38]:
df.Co2_Emissions.unique()

array(['8,672', '4,536', '150,006', '469', '34,693', '557', '201,348',
       '5,156', '375,908', '61,448', '37,620', '1,786', '31,694',
       '84,246', '1,276', '58,280', '96,889', '568', '6,476', '1,261',
       '21,606', '21,848', '6,340', '462,299', '7,664', '41,708', '3,418',
       '495', '9,674', '543', '9,919', '8,291', '544,894', '297', '1,016',
       '85,822', '9,893,038', '97,814', '202', '3,282', '8,023', '17,488',
       '28,284', '6,626', '102,218', '2,021', '31,786', '620', '180',
       '25,258', '41,155', '238,560', '7,169', '5,655', '711', '16,590',
       0, '14,870', '2,046', '45,871', '303,276', '5,321', '532',
       '10,128', '727,973', '16,670', '62,434', '268', '16,777', '2,996',
       '293', '2,384', '2,978', '9,813', '45,537', '2,065', '2,407,672',
       '563,325', '661,710', '190,061', '37,711', '65,166', '320,411',
       '8,225', '1,135,886', '25,108', '247,207', '17,910', '66',
       '98,734', '9,787', '17,763', '7,004', '24,796', '2,512', '1,386',
 

In [39]:
df.Co2_Emissions = df.Co2_Emissions.replace('[,]','', regex=True).astype('int64')

In [40]:
df.Co2_Emissions.unique()

array([   8672,    4536,  150006,     469,   34693,     557,  201348,
          5156,  375908,   61448,   37620,    1786,   31694,   84246,
          1276,   58280,   96889,     568,    6476,    1261,   21606,
         21848,    6340,  462299,    7664,   41708,    3418,     495,
          9674,     543,    9919,    8291,  544894,     297,    1016,
         85822, 9893038,   97814,     202,    3282,    8023,   17488,
         28284,    6626,  102218,    2021,   31786,     620,     180,
         25258,   41155,  238560,    7169,    5655,     711,   16590,
             0,   14870,    2046,   45871,  303276,    5321,     532,
         10128,  727973,   16670,   62434,     268,   16777,    2996,
           293,    2384,    2978,    9813,   45537,    2065, 2407672,
        563325,  661710,  190061,   37711,   65166,  320411,    8225,
       1135886,   25108,  247207,   17910,      66,   98734,    9787,
         17763,    7004,   24796,    2512,    1386,   50564,      51,
         12963,    8

In [41]:
df.Agricultural_Land.unique()

array(['58.10%', '43.10%', '17.40%', '40.00%', '47.50%', '20.50%',
       '54.30%', '58.90%', '48.20%', '32.40%', '57.70%', '1.40%',
       '11.10%', '70.60%', '23.30%', '42.00%', '44.60%', '7.00%',
       '33.30%', '13.60%', '34.80%', '45.60%', '33.90%', '2.70%',
       '46.30%', '44.20%', '79.20%', '64.80%', '19.60%', '30.90%',
       '20.60%', '6.90%', '8.20%', '39.70%', '21.20%', '56.20%', '40.30%',
       '71.50%', '31.10%', '34.50%', '27.60%', '59.90%', '12.20%',
       '45.20%', '11.60%', '62.00%', '73.40%', '48.70%', '22.20%',
       '3.80%', '76.40%', '10.10%', '75.20%', '23.10%', 0, '36.30%',
       '7.50%', '52.40%', '20.00%', '59.80%', '47.70%', '69.00%',
       '47.60%', '23.50%', '36.00%', '59.00%', '58.00%', '8.60%',
       '66.80%', '28.90%', '58.40%', '18.70%', '60.40%', '31.50%',
       '28.20%', '21.40%', '64.50%', '24.60%', '43.20%', '41.00%',
       '12.30%', '12.00%', '80.40%', '48.50%', '8.40%', '55.00%',
       '10.30%', '64.30%', '77.60%', '28.00%', '8.70%', '3

In [42]:
df.Agricultural_Land = df.Agricultural_Land.replace('[%]','', regex=True).astype('float64')

In [43]:
df.Agricultural_Land.unique()

array([58.1, 43.1, 17.4, 40. , 47.5, 20.5, 54.3, 58.9, 48.2, 32.4, 57.7,
        1.4, 11.1, 70.6, 23.3, 42. , 44.6,  7. , 33.3, 13.6, 34.8, 45.6,
       33.9,  2.7, 46.3, 44.2, 79.2, 64.8, 19.6, 30.9, 20.6,  6.9,  8.2,
       39.7, 21.2, 56.2, 40.3, 71.5, 31.1, 34.5, 27.6, 59.9, 12.2, 45.2,
       11.6, 62. , 73.4, 48.7, 22.2,  3.8, 76.4, 10.1, 75.2, 23.1,  0. ,
       36.3,  7.5, 52.4, 20. , 59.8, 47.7, 69. , 47.6, 23.5, 36. , 59. ,
       58. ,  8.6, 66.8, 28.9, 58.4, 18.7, 60.4, 31.5, 28.2, 21.4, 64.5,
       24.6, 43.2, 41. , 12.3, 12. , 80.4, 48.5,  8.4, 55. , 10.3, 64.3,
       77.6, 28. ,  8.7, 32.2, 47.2, 53.7, 71.2, 61.4, 26.3, 33.8, 63.9,
       38.5, 42.4, 54.6, 31.4, 74.2, 19. , 68.5, 63.5, 19.5, 47.1, 28.7,
       53.3, 40.5, 42.1, 36.1, 77.7, 21.8,  4.6, 47.8, 10.9, 30.4,  2.6,
       55.1, 18.5, 41.7, 46.9, 39.5,  5.8, 58.8, 13.3, 25.6, 12.4, 16.7,
       50.7, 80.8, 46.1, 39.3,  3.4, 54.7,  0.9, 39.2, 30.7,  3.9, 70.3,
       79.8, 52.6, 43.7,  0.6,  7.4, 38.4, 75.8, 34

In [44]:
df[['Agricultural_Land', 'Density', 'Co2_Emissions']].corr()

Agricultural_Land   Density  Co2_Emissions
Agricultural_Land           1.000000 -0.156662       0.071776
Density                    -0.156662  1.000000      -0.020301
Co2_Emissions               0.071776 -0.020301       1.000000

5. Land Area

In [45]:
df.Land_Area.unique()

array([   6520230,     280748,  203810741,        468,  102460700,
              443,  207800400,     290743,  707410220,     830871,
           860600,     130880,        765,    1480460,        430,
          2070600,     300528,     220966,    1120622,     380394,
        100980581,     510197,    5810730,  805150770,      50765,
          1100879,    2740200,     270830,    3220463,      40033,
          1810035,    4750440,  909840670,    6220984,  102840000,
          7560096,  905960960,  101380910,      20235,    3420000,
           510100,     560594,    1100860,      90251,     780867,
        203440858,     430094,     230200,        751,     480670,
          2830561,  100010450,     210041,     280051,    1170600,
           450228,     170364,  101040300,     180274,    3380145,
          6430801,    2670667,     110300,     690700,    3570022,
          2380533,    1310957,        349,    1080889,    2450857,
           360125,    2140969,     270750,          0,    1120

In [46]:
df["Land_Area"].max() -  df["Land_Area"].min() 

1700980240

In [47]:
df[["Land_Area", "Density"]].corr()

Land_Area  Density
Land_Area    1.00000 -0.04038
Density     -0.04038  1.00000

6. Armed Forces

In [48]:
df["Armed_Forces_size"].describe()

count     195
unique    106
top         0
freq       24
Name: Armed_Forces_size, dtype: int64

In [49]:
df.Population.unique()

array(['38,041,754', '2,854,191', '43,053,054', '77,142', '31,825,295',
       '97,118', '44,938,712', '2,957,731', '25,766,605', '8,877,067',
       '10,023,318', '389,482', '1,501,635', '167,310,838', '287,025',
       '9,466,856', '11,484,055', '390,353', '11,801,151', '727,145',
       '11,513,100', '3,301,000', '2,346,179', '212,559,417', '433,285',
       '6,975,761', '20,321,378', '11,530,580', '25,716,544', '483,628',
       '16,486,542', '25,876,380', '36,991,981', '4,745,185',
       '15,946,876', '18,952,038', '1,397,715,000', '50,339,443',
       '850,886', '5,380,508', '5,047,561', '4,067,500', '11,333,483',
       '1,198,575', '10,669,709', '86,790,567', '5,818,553', '973,560',
       '71,808', '10,738,958', '17,373,662', '100,388,073', '6,453,553',
       '1,355,986', '6,333,135', '1,331,824', '1,093,238', '112,078,730',
       '889,953', '5,520,314', '67,059,887', '2,172,579', '2,347,706',
       '3,720,382', '83,132,799', '30,792,608', '10,716,322', '112,003',
       '

In [50]:
df.Population = df.Population.replace('[,]','', regex=True).astype('int64')

In [51]:
df.Population.unique()

array([  38041754,    2854191,   43053054,      77142,   31825295,
            97118,   44938712,    2957731,   25766605,    8877067,
         10023318,     389482,    1501635,  167310838,     287025,
          9466856,   11484055,     390353,   11801151,     727145,
         11513100,    3301000,    2346179,  212559417,     433285,
          6975761,   20321378,   11530580,   25716544,     483628,
         16486542,   25876380,   36991981,    4745185,   15946876,
         18952038, 1397715000,   50339443,     850886,    5380508,
          5047561,    4067500,   11333483,    1198575,   10669709,
         86790567,    5818553,     973560,      71808,   10738958,
         17373662,  100388073,    6453553,    1355986,    6333135,
          1331824,    1093238,  112078730,     889953,    5520314,
         67059887,    2172579,    2347706,    3720382,   83132799,
         30792608,   10716322,     112003,   16604026,   12771246,
          1920922,     782766,   11263077,        836,    9746

In [52]:
df.Armed_Forces_size.unique()

array(['323,000', '9,000', '317,000', 0, '117,000', '0', '105,000',
       '49,000', '58,000', '21,000', '82,000', '1,000', '19,000',
       '221,000', '155,000', '32,000', '2,000', '12,000', '6,000',
       '71,000', '11,000', '730,000', '8,000', '31,000', '27,000',
       '191,000', '24,000', '72,000', '35,000', '122,000', '2,695,000',
       '481,000', '10,000', '18,000', '76,000', '16,000', '23,000',
       '134,000', '15,000', '13,000', '41,000', '836,000', '42,000',
       '202,000', '138,000', '4,000', '25,000', '307,000', '7,000',
       '26,000', '180,000', '146,000', '43,000', '3,000', '40,000',
       '3,031,000', '676,000', '563,000', '209,000', '178,000', '347,000',
       '261,000', '116,000', '29,000', '129,000', '80,000', '34,000',
       '22,000', '136,000', '5,000', '336,000', '246,000', '513,000',
       '112,000', '215,000', '1,469,000', '47,000', '936,000', '158,000',
       '153,000', '52,000', '126,000', '1,454,000', '252,000', '81,000',
       '20,000', '634,000

In [53]:
df.Armed_Forces_size = df.Armed_Forces_size.replace('[,]','', regex=True).astype('int64')

In [54]:
df.Armed_Forces_size.unique()

array([ 323000,    9000,  317000,       0,  117000,  105000,   49000,
         58000,   21000,   82000,    1000,   19000,  221000,  155000,
         32000,    2000,   12000,    6000,   71000,   11000,  730000,
          8000,   31000,   27000,  191000,   24000,   72000,   35000,
        122000, 2695000,  481000,   10000,   18000,   76000,   16000,
         23000,  134000,   15000,   13000,   41000,  836000,   42000,
        202000,  138000,    4000,   25000,  307000,    7000,   26000,
        180000,  146000,   43000,    3000,   40000, 3031000,  676000,
        563000,  209000,  178000,  347000,  261000,  116000,   29000,
        129000,   80000,   34000,   22000,  136000,    5000,  336000,
        246000,  513000,  112000,  215000, 1469000,   47000,  936000,
        158000,  153000,   52000,  126000, 1454000,  252000,   81000,
         20000,  634000,  185000,  196000,  124000,   30000,  239000,
         17000,   28000,  455000,   48000,  512000,   46000,  297000,
         63000,  148

In [55]:
df[["Armed_Forces_size", "Population", "Land_Area"]].corr()

Armed_Forces_size  Population  Land_Area
Armed_Forces_size           1.000000    0.876850   0.550426
Population                  0.876850    1.000000   0.434808
Land_Area                   0.550426    0.434808   1.000000

7. Birth Rate

In [56]:
df["Birth_Rate"].max() - df["Birth_Rate"].min()

46.08

In [57]:
df.GDP.unique()

array(['$19,101,353,833 ', '$15,278,077,447 ', '$169,988,236,398 ',
       '$3,154,057,987 ', '$94,635,415,870 ', '$1,727,759,259 ',
       '$449,663,446,954 ', '$13,672,802,158 ', '$1,392,680,589,329 ',
       '$446,314,739,528 ', '$39,207,000,000 ', '$12,827,000,000 ',
       '$38,574,069,149 ', '$302,571,254,131 ', '$5,209,000,000 ',
       '$63,080,457,023 ', '$529,606,710,418 ', '$1,879,613,600 ',
       '$14,390,709,095 ', '$2,446,674,101 ', '$40,895,322,865 ',
       '$20,047,848,435 ', '$18,340,510,789 ', '$1,839,758,040,766 ',
       '$13,469,422,941 ', '$86,000,000,000 ', '$15,745,810,235 ',
       '$3,012,334,882 ', '$58,792,205,642 ', '$1,981,845,741 ',
       '$27,089,389,787 ', '$38,760,467,033 ', '$1,736,425,629,520 ',
       '$2,220,307,369 ', '$11,314,951,343 ', '$282,318,159,745 ',
       '$19,910,000,000,000 ', '$323,802,808,108 ', '$1,185,728,677 ',
       '$10,820,591,131 ', '$61,773,944,174 ', '$60,415,553,039 ',
       '$100,023,000,000 ', '$24,564,647,935 ', '$2

In [58]:
df.GDP = df.GDP.replace('[$,]','', regex=True).astype('int64')

In [59]:
df.GDP.unique()

array([   19101353833,    15278077447,   169988236398,     3154057987,
          94635415870,     1727759259,   449663446954,    13672802158,
        1392680589329,   446314739528,    39207000000,    12827000000,
          38574069149,   302571254131,     5209000000,    63080457023,
         529606710418,     1879613600,    14390709095,     2446674101,
          40895322865,    20047848435,    18340510789,  1839758040766,
          13469422941,    86000000000,    15745810235,     3012334882,
          58792205642,     1981845741,    27089389787,    38760467033,
        1736425629520,     2220307369,    11314951343,   282318159745,
       19910000000000,   323802808108,     1185728677,    10820591131,
          61773944174,    60415553039,   100023000000,    24564647935,
         246489245495,    47319624204,   348078018464,     3318716359,
            596033333,    88941298258,   107435665000,   303175127598,
          27022640000,    11026774945,     2065001626,    31386949981,
      

In [60]:
df[["Birth_Rate", "GDP", "Population", "Density"]].corr()

Birth_Rate       GDP  Population   Density
Birth_Rate    1.000000 -0.157436   -0.034026 -0.147221
GDP          -0.157436  1.000000    0.632544 -0.018878
Population   -0.034026  0.632544    1.000000 -0.017946
Density      -0.147221 -0.018878   -0.017946  1.000000

8. Calling Codes

In [61]:
df[["Country", "Calling_Code"]]

Country  Calling_Code
0    Afghanistan          93.0
1        Albania         355.0
2        Algeria         213.0
3        Andorra         376.0
4         Angola         244.0
..           ...           ...
190    Venezuela          58.0
191      Vietnam          84.0
192        Yemen         967.0
193       Zambia         260.0
194     Zimbabwe         263.0

[195 rows x 2 columns]

In [62]:
df["Region_Code"] = df["Calling_Code"]

In [63]:
df[["Country", "Calling_Code", "Region_Code"]]

Country  Calling_Code  Region_Code
0    Afghanistan          93.0         93.0
1        Albania         355.0        355.0
2        Algeria         213.0        213.0
3        Andorra         376.0        376.0
4         Angola         244.0        244.0
..           ...           ...          ...
190    Venezuela          58.0         58.0
191      Vietnam          84.0         84.0
192        Yemen         967.0        967.0
193       Zambia         260.0        260.0
194     Zimbabwe         263.0        263.0

[195 rows x 3 columns]

9. Capital/Major City

In [64]:
df[["Country", "Major_City"]]

Country        Major_City
0    Afghanistan             Kabul
1        Albania            Tirana
2        Algeria           Algiers
3        Andorra  Andorra la Vella
4         Angola            Luanda
..           ...               ...
190    Venezuela           Caracas
191      Vietnam             Hanoi
192        Yemen             Sanaa
193       Zambia            Lusaka
194     Zimbabwe            Harare

[195 rows x 2 columns]

In [65]:
df.Major_City.unique()

array(['Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
       "St. John's, Saint John", 'Buenos Aires', 'Yerevan', 'Canberra',
       'Vienna', 'Baku', 'Nassau, Bahamas', 'Manama', 'Dhaka',
       'Bridgetown', 'Minsk', 'City of Brussels', 'Belmopan',
       'Porto-Novo', 'Thimphu', 'Sucre', 'Sarajevo', 'Gaborone',
       'Bras���', 'Bandar Seri Begawan', 'Sofia', 'Ouagadougou',
       'Bujumbura', 'Yamoussoukro', 'Praia', 'Phnom Penh', 'Yaound�',
       'Ottawa', 'Bangui', "N'Djamena", 'Santiago', 'Beijing', 'Bogot�',
       'Moroni, Comoros', 'Brazzaville', 'San Jos������', 'Zagreb',
       'Havana', 'Nicosia', 'Prague', 'Kinshasa', 'Copenhagen',
       'Djibouti City', 'Roseau', 'Santo Domingo', 'Quito', 'Cairo',
       'San Salvador', 'Malabo', 'Asmara', 'Tallinn', 'Mbabane',
       'Addis Ababa', 'Suva', 'Helsinki', 'Paris', 'Libreville', 'Banjul',
       'Tbilisi', 'Berlin', 'Accra', 'Athens', "St. George's, Grenada",
       'Guatemala City', 'Conakry', 'Bissau', 'Geo

In [66]:
df.Major_City = df.Major_City.replace('[�]', '', regex=True).astype('object')

In [67]:
df.Major_City.unique()

array(['Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
       "St. John's, Saint John", 'Buenos Aires', 'Yerevan', 'Canberra',
       'Vienna', 'Baku', 'Nassau, Bahamas', 'Manama', 'Dhaka',
       'Bridgetown', 'Minsk', 'City of Brussels', 'Belmopan',
       'Porto-Novo', 'Thimphu', 'Sucre', 'Sarajevo', 'Gaborone', 'Bras',
       'Bandar Seri Begawan', 'Sofia', 'Ouagadougou', 'Bujumbura',
       'Yamoussoukro', 'Praia', 'Phnom Penh', 'Yaound', 'Ottawa',
       'Bangui', "N'Djamena", 'Santiago', 'Beijing', 'Bogot',
       'Moroni, Comoros', 'Brazzaville', 'San Jos', 'Zagreb', 'Havana',
       'Nicosia', 'Prague', 'Kinshasa', 'Copenhagen', 'Djibouti City',
       'Roseau', 'Santo Domingo', 'Quito', 'Cairo', 'San Salvador',
       'Malabo', 'Asmara', 'Tallinn', 'Mbabane', 'Addis Ababa', 'Suva',
       'Helsinki', 'Paris', 'Libreville', 'Banjul', 'Tbilisi', 'Berlin',
       'Accra', 'Athens', "St. George's, Grenada", 'Guatemala City',
       'Conakry', 'Bissau', 'Georgetown, Gu

In [68]:
df.groupby("Major_City")[["Population", "GDP", "Land_Area"]].sum()

Population           GDP  Land_Area
Major_City                                         
0                 12481021  424138778437  107591256
Abu Dhabi          9770529  421142267938     830600
Abuja            200963599  448120428859    9230768
Accra             30792608   66983634224    2380533
Addis Ababa      112078730   96107662398  101040300
...                    ...           ...        ...
Yamoussoukro      25716544   58792205642    3220463
Yaound            25876380   38760467033    4750440
Yaren District       10084     133000000         21
Yerevan            2957731   13672802158     290743
Zagreb             4067500   60415553039     560594

[193 rows x 3 columns]

10. CO2Emissions

In [69]:
df["Co2_Emissions"].describe()

count    1.950000e+02
mean     1.714167e+05
std      8.241858e+05
min      0.000000e+00
25%      1.901500e+03
50%      1.071500e+04
75%      6.194100e+04
max      9.893038e+06
Name: Co2_Emissions, dtype: float64

In [70]:
df[["Co2_Emissions", "Population", "GDP"]].corr()

Co2_Emissions  Population       GDP
Co2_Emissions       1.000000    0.810285  0.916996
Population          0.810285    1.000000  0.632544
GDP                 0.916996    0.632544  1.000000

11. Health Expenditure

In [71]:
df["Out_of_pocket_health_expenditure"].describe()

count     195
unique    161
top         0
freq        7
Name: Out_of_pocket_health_expenditure, dtype: int64

In [72]:
df.Out_of_pocket_health_expenditure.unique()

array(['78.40%', '56.90%', '28.10%', '36.40%', '33.40%', '24.30%',
       '17.60%', '81.60%', '19.60%', '17.90%', '78.60%', '27.80%',
       '25.10%', '71.80%', '45.20%', '34.50%', '22.70%', '40.50%',
       '19.80%', '25.90%', '28.60%', '5.30%', '28.30%', '6.00%', '47.70%',
       '36.10%', '19.10%', '36.00%', '23.20%', '59.40%', '69.70%',
       '14.60%', '39.60%', '56.40%', '32.20%', '32.40%', '18.30%',
       '74.80%', '43.80%', '21.50%', '15.20%', 0, '43.90%', '14.80%',
       '37.40%', '13.70%', '20.40%', '28.40%', '43.70%', '62.00%',
       '27.90%', '72.00%', '52.40%', '22.80%', '11.30%', '37.80%',
       '21.40%', '19.90%', '6.80%', '20.30%', '57.30%', '12.50%',
       '35.50%', '57.00%', '55.80%', '54.50%', '37.20%', '36.30%',
       '49.10%', '29.00%', '17.00%', '65.10%', '48.30%', '39.70%',
       '76.50%', '24.40%', '23.70%', '13.10%', '38.80%', '0.20%',
       '14.40%', '48.20%', '45.40%', '41.60%', '32.10%', '16.90%',
       '36.70%', '10.60%', '21.70%', '11.00%', '16.40

In [73]:
df.Out_of_pocket_health_expenditure = df.Out_of_pocket_health_expenditure.replace('[%]', '', regex=True).astype('float64')

In [74]:
df.Out_of_pocket_health_expenditure.unique()

array([78.4, 56.9, 28.1, 36.4, 33.4, 24.3, 17.6, 81.6, 19.6, 17.9, 78.6,
       27.8, 25.1, 71.8, 45.2, 34.5, 22.7, 40.5, 19.8, 25.9, 28.6,  5.3,
       28.3,  6. , 47.7, 36.1, 19.1, 36. , 23.2, 59.4, 69.7, 14.6, 39.6,
       56.4, 32.2, 32.4, 18.3, 74.8, 43.8, 21.5, 15.2,  0. , 43.9, 14.8,
       37.4, 13.7, 20.4, 28.4, 43.7, 62. , 27.9, 72. , 52.4, 22.8, 11.3,
       37.8, 21.4, 19.9,  6.8, 20.3, 57.3, 12.5, 35.5, 57. , 55.8, 54.5,
       37.2, 36.3, 49.1, 29. , 17. , 65.1, 48.3, 39.7, 76.5, 24.4, 23.7,
       13.1, 38.8,  0.2, 14.4, 48.2, 45.4, 41.6, 32.1, 16.9, 36.7, 10.6,
       21.7, 11. , 16.4, 46.3, 37.1, 10. , 50.7, 41.4,  2.5, 46.2,  6.1,
       39.3, 31.8, 53.1, 73.9,  8.3, 60.4, 12.3, 12.6, 52.3, 72.2, 35.6,
       14.3,  6.4, 66.5, 21.8, 30.5,  5.8, 36.5, 30.9, 53.5, 27.7,  6.2,
       21.3, 26. , 56.6, 48.4, 11.5, 11.7, 15. , 44.2, 40.6, 38.2, 18.4,
        3.3,  7.7, 36.8, 61.3, 24.2, 38.4, 63.2, 10.1, 53.7, 63.1, 26.1,
       11.8, 10.2, 51. , 37.3, 39.8, 71.1,  0.7, 47

In [75]:
df[["Out_of_pocket_health_expenditure", "GDP", "Physicians_per_thousand"]].corr()

Out_of_pocket_health_expenditure       GDP  \
Out_of_pocket_health_expenditure                          1.000000 -0.082270   
GDP                                                      -0.082270  1.000000   
Physicians_per_thousand                                  -0.165278  0.098378   

                                  Physicians_per_thousand  
Out_of_pocket_health_expenditure                -0.165278  
GDP                                              0.098378  
Physicians_per_thousand                          1.000000

12. Physicians per Thousand

In [76]:
df["Physicians_per_thousand"].describe()

count    195.000000
mean       1.773795
std        1.688826
min        0.000000
25%        0.245000
50%        1.300000
75%        2.875000
max        8.420000
Name: Physicians_per_thousand, dtype: float64

In [77]:
df[["Physicians_per_thousand", "Life_expectancy", "Infant_mortality", "GDP"]].corr()

Physicians_per_thousand  Life_expectancy  \
Physicians_per_thousand                 1.000000         0.348046   
Life_expectancy                         0.348046         1.000000   
Infant_mortality                       -0.633198        -0.247479   
GDP                                     0.098378         0.119860   

                         Infant_mortality       GDP  
Physicians_per_thousand         -0.633198  0.098378  
Life_expectancy                 -0.247479  0.119860  
Infant_mortality                 1.000000 -0.142774  
GDP                             -0.142774  1.000000

13. Population

In [78]:
df["Population"].describe()

count    1.950000e+02
mean     3.917921e+07
std      1.447454e+08
min      0.000000e+00
25%      1.916856e+06
50%      8.776109e+06
75%      2.856227e+07
max      1.397715e+09
Name: Population, dtype: float64

In [79]:
df[["Population", "Land_Area", "GDP"]].corr()

Population  Land_Area       GDP
Population    1.000000   0.434808  0.632544
Land_Area     0.434808   1.000000  0.541467
GDP           0.632544   0.541467  1.000000

14.  Labor Force Participation

In [80]:
df["Population_Labor_force_participation"].describe()

count     195
unique    146
top         0
freq       19
Name: Population_Labor_force_participation, dtype: int64

In [81]:
df.Unemployment_rate.unique()

array(['11.12%', '12.33%', '11.70%', 0, '6.89%', '9.79%', '16.99%',
       '5.27%', '4.67%', '5.51%', '10.36%', '0.71%', '4.19%', '10.33%',
       '4.59%', '5.59%', '6.41%', '2.23%', '2.34%', '3.50%', '18.42%',
       '18.19%', '12.08%', '9.12%', '4.34%', '6.26%', '1.43%', '3.32%',
       '12.25%', '0.68%', '3.38%', '5.56%', '3.68%', '1.89%', '7.09%',
       '4.32%', '9.71%', '9.47%', '11.85%', '6.93%', '1.64%', '7.27%',
       '1.93%', '4.24%', '4.91%', '10.30%', '5.84%', '3.97%', '10.76%',
       '4.11%', '6.43%', '5.14%', '5.11%', '2.08%', '4.10%', '6.59%',
       '8.43%', '20.00%', '9.06%', '14.40%', '3.04%', '4.33%', '17.24%',
       '2.46%', '4.30%', '2.47%', '13.78%', '5.39%', '3.40%', '2.84%',
       '5.36%', '4.69%', '11.38%', '12.82%', '4.93%', '3.86%', '9.89%',
       '8.00%', '2.29%', '14.72%', '2.64%', '2.18%', '6.33%', '0.63%',
       '6.52%', '6.23%', '23.41%', '2.81%', '18.56%', '6.35%', '1.76%',
       '5.65%', '6.14%', '7.22%', '3.47%', '9.55%', '6.67%', '3.42%',
    

In [82]:
df.Unemployment_rate = df.Unemployment_rate.replace('[%]', '', regex=True).astype('float64')

In [83]:
df.Unemployment_rate.unique()

array([11.12, 12.33, 11.7 ,  0.  ,  6.89,  9.79, 16.99,  5.27,  4.67,
        5.51, 10.36,  0.71,  4.19, 10.33,  4.59,  5.59,  6.41,  2.23,
        2.34,  3.5 , 18.42, 18.19, 12.08,  9.12,  4.34,  6.26,  1.43,
        3.32, 12.25,  0.68,  3.38,  5.56,  3.68,  1.89,  7.09,  4.32,
        9.71,  9.47, 11.85,  6.93,  1.64,  7.27,  1.93,  4.24,  4.91,
       10.3 ,  5.84,  3.97, 10.76,  4.11,  6.43,  5.14,  5.11,  2.08,
        4.1 ,  6.59,  8.43, 20.  ,  9.06, 14.4 ,  3.04,  4.33, 17.24,
        2.46,  4.3 ,  2.47, 13.78,  5.39,  3.4 ,  2.84,  5.36,  4.69,
       11.38, 12.82,  4.93,  3.86,  9.89,  8.  ,  2.29, 14.72,  2.64,
        2.18,  6.33,  0.63,  6.52,  6.23, 23.41,  2.81, 18.56,  6.35,
        1.76,  5.65,  6.14,  7.22,  3.47,  9.55,  6.67,  3.42,  5.47,
        6.01, 14.88,  9.02,  3.24,  1.58, 20.27,  1.41,  3.2 ,  4.07,
        6.84,  0.47,  8.1 ,  2.74,  3.35,  2.67,  4.45,  3.9 ,  4.81,
        3.31,  2.15,  0.09,  3.98,  1.03, 20.71, 18.88,  8.36, 13.37,
        5.93,  6.6 ,

In [84]:
df.Population_Labor_force_participation.unique()

array(['48.90%', '55.70%', '41.20%', 0, '77.50%', '61.30%', '55.60%',
       '65.50%', '60.70%', '66.50%', '74.60%', '73.40%', '59.00%',
       '65.20%', '64.10%', '53.60%', '65.10%', '70.90%', '66.70%',
       '71.80%', '46.40%', '70.80%', '63.90%', '64.70%', '55.40%',
       '66.40%', '79.20%', '57.00%', '60.50%', '82.30%', '76.10%',
       '72.00%', '70.70%', '62.60%', '68.00%', '68.80%', '43.30%',
       '69.40%', '62.10%', '51.20%', '63.10%', '60.60%', '63.50%',
       '62.20%', '60.20%', '64.30%', '59.10%', '62.00%', '78.40%',
       '63.60%', '79.60%', '57.60%', '55.10%', '52.90%', '59.40%',
       '68.30%', '60.80%', '67.80%', '51.80%', '62.30%', '61.50%',
       '56.20%', '67.20%', '56.50%', '75.00%', '49.30%', '67.50%',
       '44.70%', '43.00%', '64.00%', '49.60%', '66.00%', '61.70%',
       '39.30%', '74.70%', '73.50%', '59.80%', '78.50%', '61.40%',
       '47.00%', '67.90%', '76.30%', '49.70%', '61.60%', '59.30%',
       '86.10%', '76.70%', '69.80%', '45.90%', '58.30%', '4

In [85]:
df.Population_Labor_force_participation = df.Population_Labor_force_participation.replace('[%]', '', regex=True).astype('float64')

In [86]:
df.Population_Labor_force_participation.unique()

array([48.9, 55.7, 41.2,  0. , 77.5, 61.3, 55.6, 65.5, 60.7, 66.5, 74.6,
       73.4, 59. , 65.2, 64.1, 53.6, 65.1, 70.9, 66.7, 71.8, 46.4, 70.8,
       63.9, 64.7, 55.4, 66.4, 79.2, 57. , 60.5, 82.3, 76.1, 72. , 70.7,
       62.6, 68. , 68.8, 43.3, 69.4, 62.1, 51.2, 63.1, 60.6, 63.5, 62.2,
       60.2, 64.3, 59.1, 62. , 78.4, 63.6, 79.6, 57.6, 55.1, 52.9, 59.4,
       68.3, 60.8, 67.8, 51.8, 62.3, 61.5, 56.2, 67.2, 56.5, 75. , 49.3,
       67.5, 44.7, 43. , 64. , 49.6, 66. , 61.7, 39.3, 74.7, 73.5, 59.8,
       78.5, 61.4, 47. , 67.9, 76.3, 49.7, 61.6, 59.3, 86.1, 76.7, 69.8,
       45.9, 58.3, 43.1, 59.7, 54.4, 45.3, 78.1, 59.5, 83.8, 69.9, 80.4,
       63.8, 72.4, 52.6, 66.6, 47.2, 72.1, 77.6, 59.6, 56.7, 58.8, 86.8,
       54.7, 61.8, 83.7, 67.1, 65.9, 43.7, 57.8, 55.9, 45.7, 54.9, 57.9,
       70.5, 58.4, 47.4, 56. , 63. , 57.5, 53.9, 48.4, 51.1, 64.6, 44.1,
       42. , 83.4, 67.3, 60. , 46.1, 52.8, 64.5, 70.3, 54.2, 82.1, 62.8,
       77.4, 38. , 83.1])

In [87]:
df[["Population_Labor_force_participation", "GDP", "Unemployment_rate"]].corr()

Population_Labor_force_participation  \
Population_Labor_force_participation                              1.000000   
GDP                                                               0.059896   
Unemployment_rate                                                 0.156049   

                                           GDP  Unemployment_rate  
Population_Labor_force_participation  0.059896           0.156049  
GDP                                   1.000000           0.056667  
Unemployment_rate                     0.056667           1.000000

15. Tax Revenue

In [88]:
df["Tax_revenue"].describe()

count     195
unique    120
top         0
freq       26
Name: Tax_revenue, dtype: int64

In [89]:
df.Tax_revenue.unique()

array(['9.30%', '18.60%', '37.20%', 0, '9.20%', '16.50%', '10.10%',
       '20.90%', '23.00%', '25.40%', '13.00%', '14.80%', '4.20%', '8.80%',
       '27.50%', '14.70%', '24.00%', '26.30%', '10.80%', '16.00%',
       '17.00%', '20.40%', '19.50%', '14.20%', '20.20%', '15.00%',
       '13.60%', '11.80%', '20.10%', '17.10%', '12.80%', '8.60%',
       '18.20%', '9.40%', '14.40%', '9.00%', '22.00%', '24.50%', '14.90%',
       '10.70%', '32.40%', '22.10%', '12.50%', '18.10%', '6.10%',
       '28.60%', '7.50%', '24.20%', '20.80%', '10.20%', '21.70%',
       '11.50%', '12.60%', '26.20%', '19.40%', '10.60%', '10.30%',
       '17.30%', '23.30%', '11.20%', '7.40%', '2.00%', '18.30%', '23.10%',
       '24.30%', '26.80%', '11.90%', '15.10%', '11.70%', '1.40%',
       '18.00%', '12.90%', '22.90%', '15.30%', '31.60%', '16.90%',
       '26.50%', '12.00%', '11.60%', '17.80%', '19.10%', '13.10%',
       '25.20%', '17.70%', '16.80%', '21.90%', '0.00%', '5.40%', '27.10%',
       '20.70%', '29.00%', '15.60

In [90]:
df.Tax_revenue = df.Tax_revenue.replace('[%]', '', regex=True).astype('float64')

In [91]:
df.Tax_revenue.unique()

array([ 9.3, 18.6, 37.2,  0. ,  9.2, 16.5, 10.1, 20.9, 23. , 25.4, 13. ,
       14.8,  4.2,  8.8, 27.5, 14.7, 24. , 26.3, 10.8, 16. , 17. , 20.4,
       19.5, 14.2, 20.2, 15. , 13.6, 11.8, 20.1, 17.1, 12.8,  8.6, 18.2,
        9.4, 14.4,  9. , 22. , 24.5, 14.9, 10.7, 32.4, 22.1, 12.5, 18.1,
        6.1, 28.6,  7.5, 24.2, 20.8, 10.2, 21.7, 11.5, 12.6, 26.2, 19.4,
       10.6, 10.3, 17.3, 23.3, 11.2,  7.4,  2. , 18.3, 23.1, 24.3, 26.8,
       11.9, 15.1, 11.7,  1.4, 18. , 12.9, 22.9, 15.3, 31.6, 16.9, 26.5,
       12. , 11.6, 17.8, 19.1, 13.1, 25.2, 17.7, 16.8, 21.9,  5.4, 27.1,
       20.7, 29. , 15.6,  1.5, 23.9,  2.5, 21.3, 10. , 14.3, 14. , 17.4,
       22.8, 14.6, 11.4, 18.5, 25.5,  8.9, 16.3, 34.1, 18.7, 29.5,  8. ,
       27.9,  9.8, 25. , 22.3, 21.1, 17.9,  0.1,  9.6, 16.2])

In [92]:
df[["Tax_revenue", "GDP"]].corr()

Tax_revenue       GDP
Tax_revenue     1.000000 -0.037143
GDP            -0.037143  1.000000

16. Total Tax Rate

In [93]:
df["Total_tax_rate"].describe()

count     195
unique    157
top         0
freq       12
Name: Total_tax_rate, dtype: int64

In [94]:
df.Total_tax_rate.unique()

array(['71.40%', '36.60%', '66.10%', 0, '49.10%', '43.00%', '106.30%',
       '22.60%', '47.40%', '51.40%', '40.70%', '33.80%', '13.80%',
       '33.40%', '35.60%', '53.30%', '55.40%', '31.10%', '48.90%',
       '35.30%', '83.70%', '23.70%', '25.10%', '65.10%', '8.00%',
       '28.30%', '41.30%', '41.20%', '50.10%', '37.50%', '23.10%',
       '57.70%', '24.50%', '73.30%', '63.50%', '34.00%', '59.20%',
       '71.20%', '219.60%', '54.30%', '58.30%', '20.50%', '22.40%',
       '46.10%', '50.70%', '23.80%', '37.90%', '32.60%', '48.80%',
       '34.40%', '44.40%', '36.40%', '79.40%', '47.80%', '37.70%',
       '32.10%', '60.70%', '47.10%', '48.40%', '9.90%', '51.90%',
       '35.20%', '69.30%', '45.50%', '30.60%', '42.70%', '39.10%',
       '31.90%', '49.70%', '30.10%', '44.70%', '30.80%', '26.10%',
       '25.30%', '59.10%', '35.10%', '46.70%', '28.60%', '28.40%',
       '37.20%', '32.70%', '13.00%', '29.00%', '24.10%', '38.10%',
       '32.20%', '13.60%', '46.20%', '21.60%', '42.60%', '2

In [95]:
df.Total_tax_rate = df.Total_tax_rate.replace('[%]', '', regex=True).astype('float64')

In [96]:
df.Total_tax_rate.unique()

array([ 71.4,  36.6,  66.1,   0. ,  49.1,  43. , 106.3,  22.6,  47.4,
        51.4,  40.7,  33.8,  13.8,  33.4,  35.6,  53.3,  55.4,  31.1,
        48.9,  35.3,  83.7,  23.7,  25.1,  65.1,   8. ,  28.3,  41.3,
        41.2,  50.1,  37.5,  23.1,  57.7,  24.5,  73.3,  63.5,  34. ,
        59.2,  71.2, 219.6,  54.3,  58.3,  20.5,  22.4,  46.1,  50.7,
        23.8,  37.9,  32.6,  48.8,  34.4,  44.4,  36.4,  79.4,  47.8,
        37.7,  32.1,  60.7,  47.1,  48.4,   9.9,  51.9,  35.2,  69.3,
        45.5,  30.6,  42.7,  39.1,  31.9,  49.7,  30.1,  44.7,  30.8,
        26.1,  25.3,  59.1,  35.1,  46.7,  28.6,  28.4,  37.2,  32.7,
        13. ,  29. ,  24.1,  38.1,  32.2,  13.6,  46.2,  21.6,  42.6,
        20.4,  38.3,  34.5,  38.7,  30.2,  54.5,  44. ,  65.9,  67. ,
        22.2,  55.1,  60.5,  25.7,  45.8,  36.1,  31.2,  20.7,  41.8,
        34.6,  60.6,  47.2,  34.8,  36.2,  27.4,  33.9,  76.6,  37.1,
        35. ,  36.8,  43.1,  40.8,  39.8,  11.3,  20. ,  33.2,  34.7,
        37. ,  19.3,

In [97]:
df[["Total_tax_rate", "GDP"]].corr()

Total_tax_rate       GDP
Total_tax_rate        1.000000  0.069834
GDP                   0.069834  1.000000

17. Unemployment Rate

In [98]:
df["Unemployment_rate"].describe()

count    195.000000
mean       6.215385
std        5.240580
min        0.000000
25%        2.555000
50%        4.670000
75%        8.840000
max       28.180000
Name: Unemployment_rate, dtype: float64

In [99]:
df[["Unemployment_rate", "GDP", "Population_Labor_force_participation"]].corr()

Unemployment_rate       GDP  \
Unemployment_rate                              1.000000  0.056667   
GDP                                            0.056667  1.000000   
Population_Labor_force_participation           0.156049  0.059896   

                                      Population_Labor_force_participation  
Unemployment_rate                                                 0.156049  
GDP                                                               0.059896  
Population_Labor_force_participation                              1.000000

18.  Urban Population

In [100]:
df["Urban_population"].describe()

count     195
unique    191
top         0
freq        5
Name: Urban_population, dtype: int64

In [101]:
df.Urban_population.unique()

array(['9,797,273', '1,747,593', '31,510,100', '67,873', '21,061,025',
       '23,800', '41,339,571', '1,869,848', '21,844,756', '5,194,416',
       '5,616,165', '323,784', '1,467,109', '60,987,417', '89,431',
       '7,482,982', '11,259,082', '179,039', '5,648,149', '317,538',
       '8,033,035', '1,605,144', '1,616,550', '183,241,641', '337,711',
       '5,256,027', '6,092,349', '1,541,177', '13,176,900', '364,029',
       '3,924,621', '14,741,256', '30,628,482', '1,982,064', '3,712,273',
       '16,610,135', '842,933,962', '40,827,302', '248,152', '3,625,010',
       '4,041,885', '2,328,318', '8,739,135', '800,708', '7,887,156',
       '39,095,679', '5,119,978', '758,549', '50,830', '8,787,475',
       '11,116,711', '42,895,824', '4,694,702', '984,812', '1,149,670',
       '916,024', 0, '23,788,710', '505,048', '4,716,888', '54,123,364',
       '1,949,694', '1,453,958', '2,196,476', '64,324,835', '17,249,054',
       '8,507,474', '40,765', '8,540,945', '4,661,505', '840,922',
      

In [102]:
df.Urban_population = df.Urban_population.replace('[,]', '', regex=True).astype('int64')

In [103]:
df.Urban_population.unique()

array([  9797273,   1747593,  31510100,     67873,  21061025,     23800,
        41339571,   1869848,  21844756,   5194416,   5616165,    323784,
         1467109,  60987417,     89431,   7482982,  11259082,    179039,
         5648149,    317538,   8033035,   1605144,   1616550, 183241641,
          337711,   5256027,   6092349,   1541177,  13176900,    364029,
         3924621,  14741256,  30628482,   1982064,   3712273,  16610135,
       842933962,  40827302,    248152,   3625010,   4041885,   2328318,
         8739135,    800708,   7887156,  39095679,   5119978,    758549,
           50830,   8787475,  11116711,  42895824,   4694702,    984812,
         1149670,    916024,         0,  23788710,    505048,   4716888,
        54123364,   1949694,   1453958,   2196476,  64324835,  17249054,
         8507474,     40765,   8540945,   4661505,    840922,    208912,
         6328948,   5626433,   6999582,    339110, 471031528, 151509724,
        62509623,  27783368,   3133123,   8374393, 

In [104]:
df[["Urban_population", "GDP", "Density"]].corr()

Urban_population       GDP   Density
Urban_population          1.000000  0.784580 -0.023715
GDP                       0.784580  1.000000 -0.018878
Density                  -0.023715 -0.018878  1.000000